In [2]:
import numpy as np
from numpy import linalg as la

A = np.array([[1,7,2],[5,2,4],[6,7,6]])
v = np.array([29,64,91])
solv = la.solve(A,v)
print(solv)

[6. 1. 8.]


In [5]:
## eigen vector, eigen value
A = np.array([[16.01, 0.72],[0.72, 63.99]])
val, vec = la.eig(A)

In [6]:
val

array([15.99919793, 64.00080207])

In [7]:
vec

array([[-0.99988748, -0.01500119],
       [ 0.01500119, -0.99988748]])

In [35]:

## solve a matrix

#A1 = np.array([[6,4,6],[6,4,4],[2,1,4]])
A1 = np.array([[4,2,16],[6,6,36],[3,6,30]])

xxx = np.array([8,2,3])
solv = la.solve(A1,xxx)

In [36]:
solv

array([-1.2009599e+16, -2.4019198e+16,  6.0047995e+15])

In [18]:
## determinant 
A2 = np.array([[-15, 2, 4],[1,-10,12],[-2,-5,6]])
det = la.det(A2)
det

-159.99999999999994

In [37]:
## row reduce 
xx = np.array([[2,9,0],[8,0,-5]])
import sympy 
sympy.Matrix(xx).rref() 

(Matrix([
 [1, 0, -5/8],
 [0, 1, 5/36]]), (0, 1))

In [8]:
## inverse of a matrix
a = np.array([[1,7,2],[5,2,4],[6,7,6]])
a_inverse = la.inv(a)
a_inverse




###   Suppose that A is a m × n matrix. Then dim Null(A) + dim Col(A) = n.

###   roation matrix:
###    cos    -sin
###    sin    cos


array([[ 1.33333333,  2.33333333, -2.        ],
       [ 0.5       ,  0.5       , -0.5       ],
       [-1.91666667, -2.91666667,  2.75      ]])

In [ ]:
## module load canopy/1.6.1
## jupyter notebook

In [5]:
import numpy as np
from numpy import linalg as la
import sympy


In [9]:
a = np.array([[1,0],[12,1]])
a_inv = la.inv(a)
a_inv

array([[  1.,   0.],
       [-12.,   1.]])

In [25]:
a1 = np.array([[10,9,9],[10,2,18],[13,16,12],[17,9,2]])
sympy.Matrix(a1).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 0]]), (0, 1, 2))

In [26]:
a2 = np.array([[16.35,3.4], [3.4, 48.65]])
val,vec = la.eig(a2)

In [24]:
vec ##return为一个matrix 看横行
val

array([15.99598534, 49.00401466])

In [16]:
a3 = np.array([[-12,2,13],[-12,-3,-3],[11,-2,5]])
det = la.det(a3)
det

1046.9999999999993

In [18]:
aa = np.array([[2,-4],[0,-1],[4,-3]])
bb = np.array([[3,2,1],[-2,-1,4]])
res = np.dot(aa,bb)
res

array([[ 14,   8, -14],
       [  2,   1,  -4],
       [ 18,  11,  -8]])

In [21]:
aa = np.array([[2,8,3],[1,1,1],[7,7,5]])
bb = np.array([73,18,112])
res = la.solve(aa,bb)
res

array([6., 5., 7.])